#!/bin/bash

perf_changed="0"
cd /sys/devices/system/cpu/cpu0/cpufreq
declare -a files=( \
	"energy_performance_preference" \
	"scaling_governor" \
)

for i in ${files[@]}; do
	cpref="$i"
	if [ -f "$cpref" ]; then
		pref_val="$(cat $cpref)"
		echo "$cpref was set to: $pref_val"
		if ! [ "$pref_val" = "performance" ]; then
			echo performance > "$cpref"
			perf_changed="1"
		else
			perf_changed="0"
		fi
	else
		echo "$cpref does not exist... skipping..."
	fi
done

if [ "$perf_changed" -eq "1" ]; then
	echo "Performance is now set to maximum"
else
	echo "Nothing has been changed"
fi

exit
