#!/bin/bash

prf() { printf %s\\n "$*" ; }
xmon="0x1c00007"
xdg() { xdg-screensaver "$1" "$2" ; }

case $1 in
	("s") xdg suspend "$xmon"; xdg status;;
	("r") xdg resume "$xmon"; xdg status;;
	("a") xdg activate;;
	("l") xdg lock;;
	("i") xdg status;;
	("x") xdg reset;;
	(*) prf "(s)uspend (r)esume (a)ctivate (l)ock (i)status (x)reset";;
esac
